export const days = [
  { day: 'mon' },
  { day: 'tue' },
  { day: 'wed' },
  { day: 'thu' },
  { day: 'fri' },
  { day: 'sat' },
];

export const times = [
  { time: '6:30am - 7:30am' },
  { time: '10am - 11am' },
  { time: '11am - 12:30pm' },
  { time: '12pm - 1pm' },
  { time: '5pm - 6pm' },
  { time: '6pm - 7pm' },
  { time: '6pm - 7:30pm' },
  { time: '7pm - 8:30pm' },
  { time: '7:30pm - 8:30pm' },
  { time: '8:30pm - 9:30pm' },
];
export const monday = [
  { event: 'inter/advance' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: 'kids ii' },
  { event: 'beginner' },
  { event: '' },
  { event: 'advance' },
  { event: '' },
  { event: 'beginner' },
];
export const tuesday = [
  { event: '' },
  { event: '' },
  { event: '' },
  { event: 'beginner' },
  { event: 'kids i' },
  { event: '' },
  { event: 'inter/advance' },
  { event: '' },
  { event: 'beginner' },
  { event: '' },
];
export const wednesday = [
  { event: 'inter/advance' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: 'kids ii' },
  { event: 'beginner' },
  { event: '' },
  { event: 'advance' },
  { event: '' },
  { event: 'beginner' },
];
export const thursday = [
  { event: '' },
  { event: '' },
  { event: '' },
  { event: 'beginner' },
  { event: 'kids i' },
  { event: '' },
  { event: 'inter/advance' },
  { event: '' },
  { event: 'beginner' },
  { event: '' },
];
export const friday = [
  { event: 'inter/advance' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: 'kids ii' },
  { event: '' },
  { event: '' },
  { event: 'nogi' },
  { event: '' },
  { event: '' },
];
export const saturday = [
  { event: '' },
  { event: 'beginner' },
  { event: 'inter/advance' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: '' },
  { event: '' },
];
